// packages/vue/src/Alert.vue
<template>
  <ha-alert
    ref="elementRef"
    :variant="variant"
    :style-variant="styleVariant"
    :title="title"
    :closable="closable"
    :show-icon="showIcon"
    v-bind="$attrs"
    @alert-close="handleClose"
  >
    <slot />
    <template v-if="$slots.title" #title>
      <slot name="title" />
    </template>
    <template v-if="$slots.icon" #icon>
      <slot name="icon" />
    </template>
    <template v-if="$slots.actions" #actions>
      <slot name="actions" />
    </template>
  </ha-alert>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import type { HaAlert as HaAlertElement } from '@hidearea-design/core';

// Import the web component
import '@hidearea-design/core';

export interface AlertProps {
  /**
   * Alert variant
   * @default "info"
   */
  variant?: 'info' | 'success' | 'warning' | 'error';

  /**
   * Alert style variant
   * @default "soft"
   */
  styleVariant?: 'filled' | 'outlined' | 'soft';

  /**
   * Alert title
   */
  title?: string;

  /**
   * Show close button
   * @default false
   */
  closable?: boolean;

  /**
   * Show icon
   * @default true
   */
  showIcon?: boolean;
}

const props = withDefaults(defineProps<AlertProps>(), {
  variant: 'info',
  styleVariant: 'soft',
  title: '',
  closable: false,
  showIcon: true,
});

const emit = defineEmits<{
  close: [];
}>();

const elementRef = ref<HaAlertElement | null>(null);

onMounted(() => {
  const element = elementRef.value;
  if (!element) return;

  // Set properties
  element.variant = props.variant;
  element.styleVariant = props.styleVariant;
  if (props.title) {
    element.title = props.title;
  }
  element.closable = props.closable;
  element.showIcon = props.showIcon;
});

const handleClose = () => {
  emit('close');
};

// Expose close method
defineExpose({
  close: () => elementRef.value?.close(),
});
</script>

// packages/react/src/Alert.tsx
import React, {
  forwardRef,
  useEffect,
  useRef,
  useImperativeHandle,
} from "react";
import type { HaAlert as HaAlertElement } from "@hidearea-design/core";

// Import the web component
import "@hidearea-design/core";

export interface AlertProps extends React.HTMLAttributes<HTMLElement> {
  /**
   * Alert variant
   * @default "info"
   */
  variant?: "info" | "success" | "warning" | "error";

  /**
   * Alert style variant
   * @default "soft"
   */
  styleVariant?: "filled" | "outlined" | "soft";

  /**
   * Alert title
   */
  title?: string;

  /**
   * Show close button
   * @default false
   */
  closable?: boolean;

  /**
   * Show icon
   * @default true
   */
  showIcon?: boolean;

  /**
   * Alert content
   */
  children?: React.ReactNode;

  /**
   * Callback when alert is closed
   */
  onClose?: () => void;
}

export interface AlertRef {
  close: () => void;
}

/**
 * Alert component
 *
 * A React wrapper for the `ha-alert` web component.
 *
 * @example
 * ```tsx
 * <Alert variant="success" title="Success" closable>
 *   Your action was completed successfully.
 * </Alert>
 * ```
 */
export const Alert = forwardRef<AlertRef, AlertProps>(
  (
    {
      variant = "info",
      styleVariant = "soft",
      title,
      closable = false,
      showIcon = true,
      children,
      onClose,
      ...props
    },
    ref,
  ) => {
    const elementRef = useRef<HaAlertElement>(null);

    useImperativeHandle(ref, () => ({
      close: () => elementRef.current?.close(),
    }));

    useEffect(() => {
      const element = elementRef.current;
      if (!element) return;

      // Set properties
      element.variant = variant;
      element.styleVariant = styleVariant;
      if (title) {
        element.title = title;
      }
      element.closable = closable;
      element.showIcon = showIcon;
    }, [variant, styleVariant, title, closable, showIcon]);

    useEffect(() => {
      const element = elementRef.current;
      if (!element || !onClose) return;

      const handleClose = () => {
        onClose();
      };

      element.addEventListener("alert-close", handleClose);

      return () => {
        element.removeEventListener("alert-close", handleClose);
      };
    }, [onClose]);

    return (
      <ha-alert ref={elementRef} {...props}>
        {children}
      </ha-alert>
    );
  },
);

Alert.displayName = "Alert";

// Add TypeScript support for JSX
declare global {
  namespace JSX {
    interface IntrinsicElements {
      "ha-alert": React.DetailedHTMLProps<
        React.HTMLAttributes<HTMLElement>,
        HTMLElement
      >;
    }
  }
}
