// packages/vue/src/DataGrid.vue
<template>
  <ha-datagrid
    ref="elementRef"
    :striped="striped ? '' : undefined"
    :bordered="bordered ? '' : undefined"
    :hoverable="hoverable ? '' : undefined"
    :selectable="selectable ? '' : undefined"
    :page-size="pageSize"
    :current-page="currentPage"
    @sort-change="handleSortChange"
    @selection-change="handleSelectionChange"
    @page-change="handlePageChange"
    v-bind="$attrs"
  />
</template>

<script setup lang="ts">
import { ref, watch, onMounted } from 'vue';
import type { HaDataGrid as HaDataGridElement, DataGridColumn, DataGridRow } from '@hidearea-design/core';

export interface DataGridProps {
  columns?: DataGridColumn[];
  data?: DataGridRow[];
  striped?: boolean;
  bordered?: boolean;
  hoverable?: boolean;
  selectable?: boolean;
  pageSize?: number;
  currentPage?: number;
}

const props = withDefaults(defineProps<DataGridProps>(), {
  striped: false,
  bordered: false,
  hoverable: false,
  selectable: false,
  pageSize: 10,
  currentPage: 1,
});

const emit = defineEmits<{
  (e: 'sort-change', event: CustomEvent): void;
  (e: 'selection-change', event: CustomEvent): void;
  (e: 'page-change', event: CustomEvent): void;
}>();

const elementRef = ref<HaDataGridElement>();

const handleSortChange = (event: CustomEvent) => {
  emit('sort-change', event);
};

const handleSelectionChange = (event: CustomEvent) => {
  emit('selection-change', event);
};

const handlePageChange = (event: CustomEvent) => {
  emit('page-change', event);
};

const getSelectedRows = () => {
  return elementRef.value?.getSelectedRows() || [];
};

const clearSelection = () => {
  elementRef.value?.clearSelection();
};

// Watch for columns changes
watch(
  () => props.columns,
  (newColumns) => {
    if (elementRef.value && newColumns) {
      elementRef.value.setColumns(newColumns);
    }
  },
  { immediate: true }
);

// Watch for data changes
watch(
  () => props.data,
  (newData) => {
    if (elementRef.value && newData) {
      elementRef.value.setData(newData);
    }
  },
  { immediate: true }
);

onMounted(() => {
  if (elementRef.value) {
    if (props.columns) {
      elementRef.value.setColumns(props.columns);
    }
    if (props.data) {
      elementRef.value.setData(props.data);
    }
  }
});

defineExpose({
  element: elementRef,
  getSelectedRows,
  clearSelection,
});
</script>

// packages/react/src/DataGrid.tsx
import React, { forwardRef, useImperativeHandle, useRef, useEffect } from "react";
import type { HaDataGrid as HaDataGridElement, DataGridColumn, DataGridRow } from "@hidearea-design/core";

declare global {
  namespace JSX {
    interface IntrinsicElements {
      "ha-datagrid": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement> & {
        ref?: React.Ref<HaDataGridElement>;
        striped?: string | undefined;
        bordered?: string | undefined;
        hoverable?: string | undefined;
        selectable?: string | undefined;
        "page-size"?: number;
        "current-page"?: number;
      }, HTMLElement>;
    }
  }
}

export interface DataGridProps extends React.HTMLAttributes<HTMLElement> {
  columns?: DataGridColumn[];
  data?: DataGridRow[];
  striped?: boolean;
  bordered?: boolean;
  hoverable?: boolean;
  selectable?: boolean;
  pageSize?: number;
  currentPage?: number;
  onSortChange?: (event: CustomEvent) => void;
  onSelectionChange?: (event: CustomEvent) => void;
  onPageChange?: (event: CustomEvent) => void;
}

export interface DataGridRef {
  element: HaDataGridElement | null;
  getSelectedRows: () => number[];
  clearSelection: () => void;
}

export const DataGrid = forwardRef<DataGridRef, DataGridProps>(
  (
    {
      columns,
      data,
      striped,
      bordered,
      hoverable,
      selectable,
      pageSize,
      currentPage,
      onSortChange,
      onSelectionChange,
      onPageChange,
      ...props
    },
    ref
  ) => {
    const elementRef = useRef<HaDataGridElement>(null);

    useImperativeHandle(
      ref,
      () => ({
        element: elementRef.current,
        getSelectedRows: () => elementRef.current?.getSelectedRows() || [],
        clearSelection: () => elementRef.current?.clearSelection(),
      }),
      []
    );

    useEffect(() => {
      if (elementRef.current && columns) {
        elementRef.current.setColumns(columns);
      }
    }, [columns]);

    useEffect(() => {
      if (elementRef.current && data) {
        elementRef.current.setData(data);
      }
    }, [data]);

    useEffect(() => {
      const element = elementRef.current;
      if (!element) return;

      const handleSortChange = (e: Event) => {
        onSortChange?.(e as CustomEvent);
      };

      const handleSelectionChange = (e: Event) => {
        onSelectionChange?.(e as CustomEvent);
      };

      const handlePageChange = (e: Event) => {
        onPageChange?.(e as CustomEvent);
      };

      if (onSortChange) {
        element.addEventListener("sort-change", handleSortChange);
      }
      if (onSelectionChange) {
        element.addEventListener("selection-change", handleSelectionChange);
      }
      if (onPageChange) {
        element.addEventListener("page-change", handlePageChange);
      }

      return () => {
        if (onSortChange) {
          element.removeEventListener("sort-change", handleSortChange);
        }
        if (onSelectionChange) {
          element.removeEventListener("selection-change", handleSelectionChange);
        }
        if (onPageChange) {
          element.removeEventListener("page-change", handlePageChange);
        }
      };
    }, [onSortChange, onSelectionChange, onPageChange]);

    return (
      <ha-datagrid
        ref={elementRef}
        striped={striped ? "" : undefined}
        bordered={bordered ? "" : undefined}
        hoverable={hoverable ? "" : undefined}
        selectable={selectable ? "" : undefined}
        page-size={pageSize}
        current-page={currentPage}
        {...props}
      />
    );
  }
);

DataGrid.displayName = "DataGrid";
