// packages/vue/src/Pagination.vue
<template>
  <ha-pagination
    ref="elementRef"
    :current="current"
    :total="total"
    :page-size="pageSize"
    :variant="variant"
    :size="size"
    :show-quick-jumper="showQuickJumper"
    v-bind="$attrs"
    @page-change="handlePageChange"
  />
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';

// Import the web component
import '@hidearea-design/core';

export interface PaginationProps {
  /**
   * Current page number (1-indexed)
   * @default 1
   */
  current?: number;

  /**
   * Total number of items
   */
  total: number;

  /**
   * Number of items per page
   * @default 10
   */
  pageSize?: number;

  /**
   * Pagination variant
   * @default "default"
   */
  variant?: 'default' | 'rounded' | 'simple';

  /**
   * Pagination size
   * @default "md"
   */
  size?: 'sm' | 'md' | 'lg';

  /**
   * Show quick jumper
   * @default false
   */
  showQuickJumper?: boolean;
}

const props = withDefaults(defineProps<PaginationProps>(), {
  current: 1,
  pageSize: 10,
  variant: 'default',
  size: 'md',
  showQuickJumper: false,
});

const emit = defineEmits<{
  change: [page: number];
  'update:current': [value: number];
}>();

const elementRef = ref<HTMLElement | null>(null);

onMounted(() => {
  const element = elementRef.value;
  if (!element) return;

  element.setAttribute('current', props.current.toString());
  element.setAttribute('total', props.total.toString());
  element.setAttribute('page-size', props.pageSize.toString());
  element.setAttribute('variant', props.variant);
  element.setAttribute('size', props.size);
  if (props.showQuickJumper) {
    element.setAttribute('show-quick-jumper', '');
  }
});

const handlePageChange = (event: Event) => {
  const customEvent = event as CustomEvent<{ page: number }>;
  const page = customEvent.detail.page;
  emit('change', page);
  emit('update:current', page);
};

// Expose element reference
defineExpose({
  element: elementRef,
});
</script>

// packages/react/src/Pagination.tsx
import React, { forwardRef, useEffect, useRef } from "react";

// Import the web component
import "@hidearea-design/core";

export interface PaginationProps
  extends Omit<React.HTMLAttributes<HTMLElement>, "onChange"> {
  /**
   * Current page number (1-indexed)
   * @default 1
   */
  current?: number;

  /**
   * Total number of items
   */
  total: number;

  /**
   * Number of items per page
   * @default 10
   */
  pageSize?: number;

  /**
   * Pagination variant
   * @default "default"
   */
  variant?: "default" | "rounded" | "simple";

  /**
   * Pagination size
   * @default "md"
   */
  size?: "sm" | "md" | "lg";

  /**
   * Show quick jumper
   * @default false
   */
  showQuickJumper?: boolean;

  /**
   * Callback when page changes
   */
  onChange?: (page: number) => void;
}

/**
 * Pagination component
 *
 * A React wrapper for the `ha-pagination` web component.
 *
 * @example
 * ```tsx
 * <Pagination
 *   current={currentPage}
 *   total={100}
 *   pageSize={10}
 *   onChange={(page) => setCurrentPage(page)}
 * />
 * ```
 */
export const Pagination = forwardRef<HTMLElement, PaginationProps>(
  (
    {
      current = 1,
      total,
      pageSize = 10,
      variant = "default",
      size = "md",
      showQuickJumper = false,
      onChange,
      ...props
    },
    ref,
  ) => {
    const elementRef = useRef<HTMLElement>(null);

    useEffect(() => {
      const element = elementRef.current;
      if (!element) return;

      element.setAttribute("current", current.toString());
      element.setAttribute("total", total.toString());
      element.setAttribute("page-size", pageSize.toString());
      element.setAttribute("variant", variant);
      element.setAttribute("size", size);
      if (showQuickJumper) {
        element.setAttribute("show-quick-jumper", "");
      } else {
        element.removeAttribute("show-quick-jumper");
      }
    }, [current, total, pageSize, variant, size, showQuickJumper]);

    useEffect(() => {
      const element = elementRef.current;
      if (!element || !onChange) return;

      const handleChange = (event: Event) => {
        const customEvent = event as CustomEvent<{ page: number }>;
        onChange(customEvent.detail.page);
      };

      element.addEventListener("page-change", handleChange);

      return () => {
        element.removeEventListener("page-change", handleChange);
      };
    }, [onChange]);

    return <ha-pagination ref={ref || elementRef} {...props} />;
  },
);

Pagination.displayName = "Pagination";

// Add TypeScript support for JSX
declare global {
  namespace JSX {
    interface IntrinsicElements {
      "ha-pagination": React.DetailedHTMLProps<
        React.HTMLAttributes<HTMLElement>,
        HTMLElement
      >;
    }
  }
}
