// packages/vue/src/Tooltip.vue
<script setup lang="ts">
import { ref, onMounted, withDefaults } from 'vue';
import type { HaTooltip as HaTooltipElement } from '@hidearea-design/core';
import '@hidearea-design/core';

export interface TooltipProps {
  /**
   * Tooltip content text
   */
  content?: string;

  /**
   * Tooltip placement
   */
  placement?:
    | 'top'
    | 'top-start'
    | 'top-end'
    | 'bottom'
    | 'bottom-start'
    | 'bottom-end'
    | 'left'
    | 'left-start'
    | 'left-end'
    | 'right'
    | 'right-start'
    | 'right-end';

  /**
   * Trigger type
   */
  trigger?: 'hover' | 'focus' | 'click';

  /**
   * Tooltip variant
   */
  variant?: 'default' | 'dark' | 'light';

  /**
   * Tooltip size
   */
  size?: 'sm' | 'md' | 'lg';

  /**
   * Show arrow indicator
   */
  showArrow?: boolean;

  /**
   * Show delay in milliseconds
   */
  delay?: number;

  /**
   * Disabled state
   */
  disabled?: boolean;
}

const props = withDefaults(defineProps<TooltipProps>(), {
  placement: 'top',
  trigger: 'hover',
  variant: 'default',
  size: 'md',
  showArrow: false,
  delay: 200,
  disabled: false,
});

const emit = defineEmits<{
  show: [];
  hide: [];
}>();

const elementRef = ref<HaTooltipElement | null>(null);

onMounted(() => {
  const element = elementRef.value;
  if (!element) return;

  // Set properties
  if (props.content) {
    element.content = props.content;
  }
  element.placement = props.placement;
  element.triggerMode = props.trigger;
  element.variant = props.variant;
  element.size = props.size;
  element.showArrow = props.showArrow;
  element.delay = props.delay;
  element.disabled = props.disabled;

  // Event listeners
  element.addEventListener('show', () => {
    emit('show');
  });

  element.addEventListener('hide', () => {
    emit('hide');
  });
});
</script>

<template>
  <ha-tooltip
    :ref="elementRef"
    :content="content"
    :placement="placement"
    :trigger="trigger"
    :variant="variant"
    :size="size"
    :show-arrow="showArrow"
    :delay="delay"
    :disabled="disabled"
    v-bind="$attrs"
  >
    <slot />
    <template v-if="$slots.content" #content>
      <slot name="content" />
    </template>
  </ha-tooltip>
</template>

// packages/react/src/Tooltip.tsx
import React, { forwardRef, useEffect, useRef } from 'react';
import type { HaTooltip as HaTooltipElement } from '@hidearea-design/core';

// Import the web component
import '@hidearea-design/core';

export interface TooltipProps extends Omit<React.HTMLAttributes<HTMLElement>, 'content'> {
  /**
   * Tooltip content text
   */
  content?: string;

  /**
   * Tooltip placement
   * @default "top"
   */
  placement?:
    | 'top'
    | 'top-start'
    | 'top-end'
    | 'bottom'
    | 'bottom-start'
    | 'bottom-end'
    | 'left'
    | 'left-start'
    | 'left-end'
    | 'right'
    | 'right-start'
    | 'right-end';

  /**
   * Trigger type
   * @default "hover"
   */
  trigger?: 'hover' | 'focus' | 'click';

  /**
   * Tooltip variant
   * @default "default"
   */
  variant?: 'default' | 'dark' | 'light';

  /**
   * Tooltip size
   * @default "md"
   */
  size?: 'sm' | 'md' | 'lg';

  /**
   * Show arrow indicator
   * @default false
   */
  showArrow?: boolean;

  /**
   * Show delay in milliseconds
   * @default 200
   */
  delay?: number;

  /**
   * Disabled state
   * @default false
   */
  disabled?: boolean;

  /**
   * Custom tooltip content (JSX)
   */
  contentElement?: React.ReactNode;

  /**
   * Show event handler
   */
  onShow?: () => void;

  /**
   * Hide event handler
   */
  onHide?: () => void;

  /**
   * Trigger element (children)
   */
  children?: React.ReactNode;
}

/**
 * Tooltip component
 *
 * A React wrapper for the `ha-tooltip` web component.
 *
 * @example
 * ```tsx
 * <Tooltip content="Helpful information">
 *   <button>Hover me</button>
 * </Tooltip>
 * ```
 */
export const Tooltip = forwardRef<HTMLElement, TooltipProps>(
  (
    {
      content,
      placement = 'top',
      trigger = 'hover',
      variant = 'default',
      size = 'md',
      showArrow = false,
      delay = 200,
      disabled = false,
      contentElement,
      onShow,
      onHide,
      children,
      ...props
    },
    _ref
  ) => {
    const elementRef = useRef<HaTooltipElement>(null);

    useEffect(() => {
      const element = elementRef.current;
      if (!element) return;

      // Set properties
      if (content) {
        element.content = content;
      }
      element.placement = placement;
      element.triggerMode = trigger;
      element.variant = variant;
      element.size = size;
      element.showArrow = showArrow;
      element.delay = delay;
      element.disabled = disabled;
    }, [content, placement, trigger, variant, size, showArrow, delay, disabled]);

    useEffect(() => {
      const element = elementRef.current;
      if (!element) return;

      const handleShow = () => {
        if (onShow) {
          onShow();
        }
      };

      const handleHide = () => {
        if (onHide) {
          onHide();
        }
      };

      if (onShow) {
        element.addEventListener('show', handleShow);
      }
      if (onHide) {
        element.addEventListener('hide', handleHide);
      }

      return () => {
        if (onShow) {
          element.removeEventListener('show', handleShow);
        }
        if (onHide) {
          element.removeEventListener('hide', handleHide);
        }
      };
    }, [onShow, onHide]);

    return (
      <ha-tooltip ref={elementRef as any} {...props}>
        {children}
        {contentElement && <div slot="content">{contentElement}</div>}
      </ha-tooltip>
    );
  }
);

Tooltip.displayName = 'Tooltip';

// Add TypeScript support for JSX
declare global {
  namespace JSX {
    interface IntrinsicElements {
      'ha-tooltip': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement>;
    }
  }
}
