// packages/react/src/Badge.tsx
import React, {
  forwardRef,
  useEffect,
  useRef,
  useImperativeHandle,
} from "react";
import type { HaBadge as HaBadgeElement } from "@hidearea-design/core";

// Import the web component
import "@hidearea-design/core";

export interface BadgeProps extends React.HTMLAttributes<HTMLElement> {
  /**
   * Badge variant
   * @default "primary"
   */
  variant?: "primary" | "secondary" | "success" | "warning" | "error" | "info";

  /**
   * Badge style variant
   * @default "filled"
   */
  styleVariant?: "filled" | "outlined" | "soft";

  /**
   * Badge size
   * @default "md"
   */
  size?: "sm" | "md" | "lg";

  /**
   * Pill-shaped badge
   * @default false
   */
  pill?: boolean;

  /**
   * Dot-only badge (no content)
   * @default false
   */
  dot?: boolean;

  /**
   * Show remove button
   * @default false
   */
  removable?: boolean;

  /**
   * Badge content
   */
  children?: React.ReactNode;

  /**
   * Callback when remove button is clicked
   */
  onRemove?: () => void;
}

export interface BadgeRef {
  remove: () => void;
}

/**
 * Badge component
 *
 * A React wrapper for the `ha-badge` web component.
 *
 * @example
 * ```tsx
 * <Badge variant="success">Active</Badge>
 * <Badge variant="error" pill removable>Tag</Badge>
 * ```
 */
export const Badge = forwardRef<BadgeRef, BadgeProps>(
  (
    {
      variant = "primary",
      styleVariant = "filled",
      size = "md",
      pill = false,
      dot = false,
      removable = false,
      children,
      onRemove,
      ...props
    },
    ref,
  ) => {
    const elementRef = useRef<HaBadgeElement>(null);

    useImperativeHandle(ref, () => ({
      remove: () => elementRef.current?.remove(),
    }));

    useEffect(() => {
      const element = elementRef.current;
      if (!element) return;

      // Set properties
      element.variant = variant;
      element.styleVariant = styleVariant;
      element.size = size;
      element.pill = pill;
      element.dot = dot;
      element.removable = removable;
    }, [variant, styleVariant, size, pill, dot, removable]);

    useEffect(() => {
      const element = elementRef.current;
      if (!element || !onRemove) return;

      const handleRemove = () => {
        onRemove();
      };

      element.addEventListener("badge-remove", handleRemove);

      return () => {
        element.removeEventListener("badge-remove", handleRemove);
      };
    }, [onRemove]);

    return (
      <ha-badge ref={elementRef} {...props}>
        {children}
      </ha-badge>
    );
  },
);

Badge.displayName = "Badge";

// Add TypeScript support for JSX
declare global {
  namespace JSX {
    interface IntrinsicElements {
      "ha-badge": React.DetailedHTMLProps<
        React.HTMLAttributes<HTMLElement>,
        HTMLElement
      >;
    }
  }
}

// packages/vue/src/Badge.vue
<template>
  <ha-badge
    :ref="elementRef"
    :variant="variant"
    :style-variant="styleVariant"
    :size="size"
    :pill="pill"
    :dot="dot"
    :removable="removable"
    v-bind="$attrs"
    @badge-remove="handleRemove"
  >
    <slot />
    <template v-if="$slots.icon" #icon>
      <slot name="icon" />
    </template>
  </ha-badge>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import type { HaBadge as HaBadgeElement } from '@hidearea-design/core';

// Import the web component
import '@hidearea-design/core';

export interface BadgeProps {
  /**
   * Badge variant
   * @default "primary"
   */
  variant?: 'primary' | 'secondary' | 'success' | 'warning' | 'error' | 'info';

  /**
   * Badge style variant
   * @default "filled"
   */
  styleVariant?: 'filled' | 'outlined' | 'soft';

  /**
   * Badge size
   * @default "md"
   */
  size?: 'sm' | 'md' | 'lg';

  /**
   * Pill-shaped badge
   * @default false
   */
  pill?: boolean;

  /**
   * Dot-only badge (no content)
   * @default false
   */
  dot?: boolean;

  /**
   * Show remove button
   * @default false
   */
  removable?: boolean;
}

const props = withDefaults(defineProps<BadgeProps>(), {
  variant: 'primary',
  styleVariant: 'filled',
  size: 'md',
  pill: false,
  dot: false,
  removable: false,
});

const emit = defineEmits<{
  remove: [];
}>();

const elementRef = ref<HaBadgeElement | null>(null);

onMounted(() => {
  const element = elementRef.value;
  if (!element) return;

  // Set properties
  element.variant = props.variant;
  element.styleVariant = props.styleVariant;
  element.size = props.size;
  element.pill = props.pill;
  element.dot = props.dot;
  element.removable = props.removable;
});

const handleRemove = () => {
  emit('remove');
};

// Expose remove method
defineExpose({
  remove: () => elementRef.value?.remove(),
});
</script>
