// packages/react/src/Breadcrumb.tsx
import React, { forwardRef, useEffect, useRef } from "react";
import type { HaBreadcrumb as HaBreadcrumbElement } from "@hidearea-design/core";
import "@hidearea-design/core";

export interface BreadcrumbProps extends React.HTMLAttributes<HTMLElement> {
  separator?: "slash" | "chevron" | "arrow" | "dot";
  size?: "sm" | "md" | "lg";
  children?: React.ReactNode;
}

export const Breadcrumb = forwardRef<HTMLElement, BreadcrumbProps>(
  ({ separator = "slash", size = "md", children, ...props }, _ref) => {
    const elementRef = useRef<HaBreadcrumbElement>(null);

    useEffect(() => {
      const element = elementRef.current;
      if (!element) return;

      element.separator = separator;
      element.size = size;
    }, [separator, size]);

    return (
      <ha-breadcrumb ref={elementRef as any} {...props}>
        {children}
      </ha-breadcrumb>
    );
  },
);

Breadcrumb.displayName = "Breadcrumb";

declare global {
  namespace JSX {
    interface IntrinsicElements {
      "ha-breadcrumb": React.DetailedHTMLProps<
        React.HTMLAttributes<HTMLElement>,
        HTMLElement
      >;
      "ha-breadcrumb-item": React.DetailedHTMLProps<
        React.HTMLAttributes<HTMLElement>,
        HTMLElement
      >;
    }
  }
}

// packages/vue/src/Breadcrumb.vue
<script setup lang="ts">
import { ref, onMounted, withDefaults } from 'vue';
import type { HaBreadcrumb as HaBreadcrumbElement } from '@hidearea-design/core';
import '@hidearea-design/core';

export interface BreadcrumbProps {
  separator?: 'slash' | 'chevron' | 'arrow' | 'dot';
  size?: 'sm' | 'md' | 'lg';
}

const props = withDefaults(defineProps<BreadcrumbProps>(), {
  separator: 'slash',
  size: 'md',
});

const elementRef = ref<HaBreadcrumbElement | null>(null);

onMounted(() => {
  const element = elementRef.value;
  if (!element) return;

  element.separator = props.separator;
  element.size = props.size;
});
</script>

<template>
  <ha-breadcrumb :ref="elementRef" :separator="separator" :size="size" v-bind="$attrs">
    <slot />
  </ha-breadcrumb>
</template>
