// packages/react/src/DatePicker.tsx
import React, {
  forwardRef,
  useEffect,
  useRef,
  useImperativeHandle,
} from "react";
import type {
  HaDatePicker as HaDatePickerElement,
  DatePickerMode,
  DatePickerDate,
} from "@hidearea-design/core";

// Import the web component
import "@hidearea-design/core";

export interface DatePickerProps
  extends Omit<React.HTMLAttributes<HTMLElement>, "onChange"> {
  /**
   * Selection mode
   * @default "single"
   */
  mode?: DatePickerMode;

  /**
   * Selected date value (ISO 8601 format)
   */
  value?: string | Date;

  /**
   * Date format
   * @default "YYYY-MM-DD"
   */
  format?: string;

  /**
   * Minimum selectable date
   */
  minDate?: string | Date;

  /**
   * Maximum selectable date
   */
  maxDate?: string | Date;

  /**
   * Disabled dates
   */
  disabledDates?: (string | Date)[];

  /**
   * Disabled days of week (0=Sunday, 6=Saturday)
   */
  disabledDaysOfWeek?: number[];

  /**
   * Locale for date formatting
   * @default "en"
   */
  locale?: string;

  /**
   * First day of week (0=Sunday, 1=Monday)
   * @default 0
   */
  firstDayOfWeek?: 0 | 1;

  /**
   * Display inline (always visible)
   * @default false
   */
  inline?: boolean;

  /**
   * Show week numbers
   * @default false
   */
  showWeekNumbers?: boolean;

  /**
   * Show today button
   * @default false
   */
  showTodayButton?: boolean;

  /**
   * Show clear button
   * @default false
   */
  showClearButton?: boolean;

  /**
   * Disabled state
   * @default false
   */
  disabled?: boolean;

  /**
   * Required state
   * @default false
   */
  required?: boolean;

  /**
   * Error state
   * @default false
   */
  error?: boolean;

  /**
   * Readonly state
   * @default false
   */
  readonly?: boolean;

  /**
   * Placeholder text
   */
  placeholder?: string;

  /**
   * Label text
   */
  label?: string;

  /**
   * Helper text
   */
  helperText?: string;

  /**
   * Error message
   */
  errorText?: string;

  /**
   * Date select event handler
   */
  onDateSelect?: (event: {
    value?: Date;
    startDate?: Date;
    endDate?: Date;
    dates?: Date[];
  }) => void;

  /**
   * Date clear event handler
   */
  onDateClear?: () => void;

  /**
   * Month change event handler
   */
  onMonthChange?: (year: number, month: number) => void;

  /**
   * Calendar open event handler
   */
  onCalendarOpen?: () => void;

  /**
   * Calendar close event handler
   */
  onCalendarClose?: () => void;
}

export interface DatePickerRef {
  getValue: () => Date | null;
  setValue: (value: Date | string) => void;
  clear: () => void;
  open: () => void;
  close: () => void;
  toggle: () => void;
  goToToday: () => void;
  goToMonth: (year: number, month: number) => void;
  nextMonth: () => void;
  previousMonth: () => void;
  validate: () => boolean;
  isDateDisabled: (date: Date) => boolean;
}

/**
 * DatePicker component
 *
 * A React wrapper for the `ha-date-picker` web component.
 *
 * @example
 * ```tsx
 * <DatePicker
 *   value={selectedDate}
 *   onDateSelect={(e) => setSelectedDate(e.value)}
 *   minDate={new Date()}
 * />
 * ```
 */
export const DatePicker = forwardRef<DatePickerRef, DatePickerProps>(
  (
    {
      mode = "single",
      value,
      format = "YYYY-MM-DD",
      minDate,
      maxDate,
      disabledDates,
      disabledDaysOfWeek,
      locale = "en",
      firstDayOfWeek = 0,
      inline = false,
      showWeekNumbers = false,
      showTodayButton = false,
      showClearButton = false,
      disabled = false,
      required = false,
      error = false,
      readonly = false,
      placeholder,
      label,
      helperText,
      errorText,
      onDateSelect,
      onDateClear,
      onMonthChange,
      onCalendarOpen,
      onCalendarClose,
      ...props
    },
    ref
  ) => {
    const elementRef = useRef<HaDatePickerElement>(null);

    useImperativeHandle(ref, () => ({
      getValue: () => elementRef.current?.getValue() ?? null,
      setValue: (value: Date | string) => elementRef.current?.setValue(value),
      clear: () => elementRef.current?.clear(),
      open: () => elementRef.current?.open(),
      close: () => elementRef.current?.close(),
      toggle: () => elementRef.current?.toggle(),
      goToToday: () => elementRef.current?.goToToday(),
      goToMonth: (year: number, month: number) =>
        elementRef.current?.goToMonth(year, month),
      nextMonth: () => elementRef.current?.nextMonth(),
      previousMonth: () => elementRef.current?.previousMonth(),
      validate: () => elementRef.current?.validate() ?? false,
      isDateDisabled: (date: Date) =>
        elementRef.current?.isDateDisabled(date) ?? false,
    }));

    useEffect(() => {
      const element = elementRef.current;
      if (!element) return;

      // Set properties
      element.mode = mode;
      element.format = format;
      element.locale = locale;
      element.firstDayOfWeek = firstDayOfWeek;
      element.inline = inline;
      element.showWeekNumbers = showWeekNumbers;
      element.showTodayButton = showTodayButton;
      element.showClearButton = showClearButton;
      element.disabled = disabled;
      element.required = required;
      element.error = error;
      element.readonly = readonly;

      if (value !== undefined) {
        element.setAttribute(
          "value",
          typeof value === "string" ? value : value.toISOString()
        );
      }
      if (minDate !== undefined) {
        element.minDate =
          typeof minDate === "string" ? new Date(minDate) : minDate;
      }
      if (maxDate !== undefined) {
        element.maxDate =
          typeof maxDate === "string" ? new Date(maxDate) : maxDate;
      }
      if (placeholder) {
        element.setAttribute("placeholder", placeholder);
      }
      if (label) {
        element.setAttribute("label", label);
      }
      if (helperText) {
        element.setAttribute("helper-text", helperText);
      }
      if (errorText) {
        element.setAttribute("error-text", errorText);
      }
    }, [
      mode,
      value,
      format,
      minDate,
      maxDate,
      locale,
      firstDayOfWeek,
      inline,
      showWeekNumbers,
      showTodayButton,
      showClearButton,
      disabled,
      required,
      error,
      readonly,
      placeholder,
      label,
      helperText,
      errorText,
    ]);

    useEffect(() => {
      const element = elementRef.current;
      if (!element) return;

      const handleDateSelect = (e: Event) => {
        const customEvent = e as CustomEvent<{
          value?: Date;
          startDate?: Date;
          endDate?: Date;
          dates?: Date[];
        }>;
        onDateSelect?.(customEvent.detail);
      };

      const handleDateClear = () => {
        onDateClear?.();
      };

      const handleMonthChange = (e: Event) => {
        const customEvent = e as CustomEvent<{ year: number; month: number }>;
        onMonthChange?.(customEvent.detail.year, customEvent.detail.month);
      };

      const handleCalendarOpen = () => {
        onCalendarOpen?.();
      };

      const handleCalendarClose = () => {
        onCalendarClose?.();
      };

      element.addEventListener("date-select", handleDateSelect);
      element.addEventListener("date-clear", handleDateClear);
      element.addEventListener("month-change", handleMonthChange);
      element.addEventListener("calendar-open", handleCalendarOpen);
      element.addEventListener("calendar-close", handleCalendarClose);

      return () => {
        element.removeEventListener("date-select", handleDateSelect);
        element.removeEventListener("date-clear", handleDateClear);
        element.removeEventListener("month-change", handleMonthChange);
        element.removeEventListener("calendar-open", handleCalendarOpen);
        element.removeEventListener("calendar-close", handleCalendarClose);
      };
    }, [onDateSelect, onDateClear, onMonthChange, onCalendarOpen, onCalendarClose]);

    return <ha-date-picker ref={elementRef} {...props} />;
  }
);

DatePicker.displayName = "DatePicker";

// Export types
export type { DatePickerMode, DatePickerDate };

// packages/vue/src/DatePicker.vue
<template>
  <ha-date-picker
    ref="elementRef"
    :mode="mode"
    :value="value"
    :format="format"
    :min-date="minDate"
    :max-date="maxDate"
    :disabled-dates="disabledDates"
    :disabled-days-of-week="disabledDaysOfWeek"
    :locale="locale"
    :first-day-of-week="firstDayOfWeek"
    :inline="inline"
    :show-week-numbers="showWeekNumbers"
    :show-today-button="showTodayButton"
    :show-clear-button="showClearButton"
    :disabled="disabled"
    :required="required"
    :error="error"
    :readonly="readonly"
    @date-select="handleDateSelect"
    @date-clear="handleDateClear"
    @month-change="handleMonthChange"
    @calendar-open="handleCalendarOpen"
    @calendar-close="handleCalendarClose"
    v-bind="$attrs"
  >
    <slot />
  </ha-date-picker>
</template>

<script setup lang="ts">
import { ref, onMounted, watch } from 'vue';
import type {
  HaDatePicker as HaDatePickerElement,
  DatePickerMode,
  DatePickerDate,
} from '@hidearea-design/core';

// Import the web component
import '@hidearea-design/core';

export interface DatePickerProps {
  /**
   * Selection mode
   * @default "single"
   */
  mode?: DatePickerMode;

  /**
   * Selected date value
   */
  value?: string | Date;

  /**
   * Date format
   * @default "YYYY-MM-DD"
   */
  format?: string;

  /**
   * Minimum selectable date
   */
  minDate?: string | Date;

  /**
   * Maximum selectable date
   */
  maxDate?: string | Date;

  /**
   * Disabled dates
   */
  disabledDates?: (string | Date)[];

  /**
   * Disabled days of week (0=Sunday, 6=Saturday)
   */
  disabledDaysOfWeek?: number[];

  /**
   * Locale for date formatting
   * @default "en"
   */
  locale?: string;

  /**
   * First day of week (0=Sunday, 1=Monday)
   * @default 0
   */
  firstDayOfWeek?: 0 | 1;

  /**
   * Display inline (always visible)
   * @default false
   */
  inline?: boolean;

  /**
   * Show week numbers
   * @default false
   */
  showWeekNumbers?: boolean;

  /**
   * Show today button
   * @default false
   */
  showTodayButton?: boolean;

  /**
   * Show clear button
   * @default false
   */
  showClearButton?: boolean;

  /**
   * Disabled state
   * @default false
   */
  disabled?: boolean;

  /**
   * Required state
   * @default false
   */
  required?: boolean;

  /**
   * Error state
   * @default false
   */
  error?: boolean;

  /**
   * Readonly state
   * @default false
   */
  readonly?: boolean;

  /**
   * Placeholder text
   */
  placeholder?: string;

  /**
   * Label text
   */
  label?: string;

  /**
   * Helper text
   */
  helperText?: string;

  /**
   * Error message
   */
  errorText?: string;
}

const props = withDefaults(defineProps<DatePickerProps>(), {
  mode: 'single',
  format: 'YYYY-MM-DD',
  locale: 'en',
  firstDayOfWeek: 0,
  inline: false,
  showWeekNumbers: false,
  showTodayButton: false,
  showClearButton: false,
  disabled: false,
  required: false,
  error: false,
  readonly: false,
  disabledDates: () => [],
  disabledDaysOfWeek: () => [],
});

const emit = defineEmits<{
  'date-select': [event: {
    value?: Date;
    startDate?: Date;
    endDate?: Date;
    dates?: Date[];
  }];
  'date-clear': [];
  'month-change': [year: number, month: number];
  'calendar-open': [];
  'calendar-close': [];
}>();

const elementRef = ref<HaDatePickerElement | null>(null);

onMounted(() => {
  const element = elementRef.value;
  if (!element) return;

  // Set initial properties
  element.mode = props.mode;
  element.format = props.format;
  element.locale = props.locale;
  element.firstDayOfWeek = props.firstDayOfWeek;
  element.inline = props.inline;
  element.showWeekNumbers = props.showWeekNumbers;
  element.showTodayButton = props.showTodayButton;
  element.showClearButton = props.showClearButton;
  element.disabled = props.disabled;
  element.required = props.required;
  element.error = props.error;
  element.readonly = props.readonly;

  if (props.value) {
    element.setAttribute(
      'value',
      typeof props.value === 'string' ? props.value : props.value.toISOString()
    );
  }
  if (props.minDate) {
    element.minDate =
      typeof props.minDate === 'string' ? new Date(props.minDate) : props.minDate;
  }
  if (props.maxDate) {
    element.maxDate =
      typeof props.maxDate === 'string' ? new Date(props.maxDate) : props.maxDate;
  }
  if (props.placeholder) {
    element.setAttribute('placeholder', props.placeholder);
  }
  if (props.label) {
    element.setAttribute('label', props.label);
  }
  if (props.helperText) {
    element.setAttribute('helper-text', props.helperText);
  }
  if (props.errorText) {
    element.setAttribute('error-text', props.errorText);
  }
  if (props.disabledDates) {
    element.disabledDates = props.disabledDates;
  }
  if (props.disabledDaysOfWeek) {
    element.disabledDaysOfWeek = props.disabledDaysOfWeek;
  }
});

// Watch for prop changes
watch(
  () => props.mode,
  (newValue) => {
    if (elementRef.value) {
      elementRef.value.mode = newValue;
    }
  }
);

watch(
  () => props.disabled,
  (newValue) => {
    if (elementRef.value) {
      elementRef.value.disabled = newValue;
    }
  }
);

watch(
  () => props.required,
  (newValue) => {
    if (elementRef.value) {
      elementRef.value.required = newValue;
    }
  }
);

watch(
  () => props.error,
  (newValue) => {
    if (elementRef.value) {
      elementRef.value.error = newValue;
    }
  }
);

watch(
  () => props.readonly,
  (newValue) => {
    if (elementRef.value) {
      elementRef.value.readonly = newValue;
    }
  }
);

watch(
  () => props.inline,
  (newValue) => {
    if (elementRef.value) {
      elementRef.value.inline = newValue;
    }
  }
);

watch(
  () => props.disabledDates,
  (newValue) => {
    if (elementRef.value) {
      elementRef.value.disabledDates = newValue;
    }
  },
  { deep: true }
);

watch(
  () => props.disabledDaysOfWeek,
  (newValue) => {
    if (elementRef.value) {
      elementRef.value.disabledDaysOfWeek = newValue;
    }
  },
  { deep: true }
);

// Event handlers
const handleDateSelect = (e: Event) => {
  const customEvent = e as CustomEvent<{
    value?: Date;
    startDate?: Date;
    endDate?: Date;
    dates?: Date[];
  }>;
  emit('date-select', customEvent.detail);
};

const handleDateClear = () => {
  emit('date-clear');
};

const handleMonthChange = (e: Event) => {
  const customEvent = e as CustomEvent<{ year: number; month: number }>;
  emit('month-change', customEvent.detail.year, customEvent.detail.month);
};

const handleCalendarOpen = () => {
  emit('calendar-open');
};

const handleCalendarClose = () => {
  emit('calendar-close');
};

// Expose methods
defineExpose({
  getValue: () => elementRef.value?.getValue() ?? null,
  setValue: (value: Date | string) => elementRef.value?.setValue(value),
  clear: () => elementRef.value?.clear(),
  open: () => elementRef.value?.open(),
  close: () => elementRef.value?.close(),
  toggle: () => elementRef.value?.toggle(),
  goToToday: () => elementRef.value?.goToToday(),
  goToMonth: (year: number, month: number) => elementRef.value?.goToMonth(year, month),
  nextMonth: () => elementRef.value?.nextMonth(),
  previousMonth: () => elementRef.value?.previousMonth(),
  validate: () => elementRef.value?.validate() ?? false,
  isDateDisabled: (date: Date) => elementRef.value?.isDateDisabled(date) ?? false,
});
</script>
